#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlApp.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbo.Receipts")]
	public partial class ContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAREA(AREA instance);
    partial void UpdateAREA(AREA instance);
    partial void DeleteAREA(AREA instance);
    partial void InsertCUSTOMER(CUSTOMER instance);
    partial void UpdateCUSTOMER(CUSTOMER instance);
    partial void DeleteCUSTOMER(CUSTOMER instance);
    partial void InsertPRICE_TAG(PRICE_TAG instance);
    partial void UpdatePRICE_TAG(PRICE_TAG instance);
    partial void DeletePRICE_TAG(PRICE_TAG instance);
    partial void InsertRECEIPT(RECEIPT instance);
    partial void UpdateRECEIPT(RECEIPT instance);
    partial void DeleteRECEIPT(RECEIPT instance);
    partial void InsertUSER(USER instance);
    partial void UpdateUSER(USER instance);
    partial void DeleteUSER(USER instance);
    #endregion
		
		public ContextDataContext() : 
				base(global::ControlApp.DataAccess.Properties.Settings.Default.dbo_ReceiptsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AREA> AREAs
		{
			get
			{
				return this.GetTable<AREA>();
			}
		}
		
		public System.Data.Linq.Table<AUTHENTICATION> AUTHENTICATIONs
		{
			get
			{
				return this.GetTable<AUTHENTICATION>();
			}
		}
		
		public System.Data.Linq.Table<CUSTOMER> CUSTOMERs
		{
			get
			{
				return this.GetTable<CUSTOMER>();
			}
		}
		
		public System.Data.Linq.Table<PRICE_TAG> PRICE_TAGs
		{
			get
			{
				return this.GetTable<PRICE_TAG>();
			}
		}
		
		public System.Data.Linq.Table<RECEIPT> RECEIPTs
		{
			get
			{
				return this.GetTable<RECEIPT>();
			}
		}
		
		public System.Data.Linq.Table<USER> USERs
		{
			get
			{
				return this.GetTable<USER>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CREATE_AREA")]
		public int SP_CREATE_AREA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string pAREA_NAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pAREA_NAME);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CREATE_AUTHENTICATION")]
		public int SP_CREATE_AUTHENTICATION([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_USER, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string pUSER_NICKNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string pPASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_AREA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_USER, pUSER_NICKNAME, pPASSWORD, pID_AREA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CREATE_CUSTOMER")]
		public int SP_CREATE_CUSTOMER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_CUSTOMER, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string pCUSTOMER_NAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_CUSTOMER, pCUSTOMER_NAME);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CREATE_PRICE_TAG")]
		public int SP_CREATE_PRICE_TAG([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> pTOTAL_PRICE, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string pDESCRIP_PRICE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pTOTAL_PRICE, pDESCRIP_PRICE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CREATE_RECEIPT")]
		public int SP_CREATE_RECEIPT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string pCUSTOMER_NAME, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> pDATE_RECEIPT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pQUANTITY, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> pTOTAL_RECEIPT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_PRICE_TAG, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_USER)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pCUSTOMER_NAME, pDATE_RECEIPT, pQUANTITY, pTOTAL_RECEIPT, pID_PRICE_TAG, pID_USER);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CREATE_USER")]
		public int SP_CREATE_USER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_USER, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string pUSER_NAME, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_AREA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_USER, pUSER_NAME, pID_AREA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DELETE_AREA")]
		public int SP_DELETE_AREA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_AREA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_AREA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DELETE_AUTHENTICATION")]
		public int SP_DELETE_AUTHENTICATION([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_USER)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_USER);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DELETE_CUSTOMER")]
		public int SP_DELETE_CUSTOMER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_CUSTOMER)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_CUSTOMER);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DELETE_PRICE_TAG")]
		public int SP_DELETE_PRICE_TAG([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_PRICE_TAG)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_PRICE_TAG);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DELETE_RECEIPT")]
		public int SP_DELETE_RECEIPT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_RECEIPT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_RECEIPT);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DELETE_USER")]
		public int SP_DELETE_USER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_USER)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_USER);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_pRETRIEVE_ALL_CUSTOMER")]
		public ISingleResult<SP_pRETRIEVE_ALL_CUSTOMERResult> SP_pRETRIEVE_ALL_CUSTOMER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string pCUSTOMER_NAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pCUSTOMER_NAME);
			return ((ISingleResult<SP_pRETRIEVE_ALL_CUSTOMERResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_pRETRIEVE_ALL_RECEIPT")]
		public ISingleResult<SP_pRETRIEVE_ALL_RECEIPTResult> SP_pRETRIEVE_ALL_RECEIPT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_RECEIPT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_RECEIPT);
			return ((ISingleResult<SP_pRETRIEVE_ALL_RECEIPTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_pRETRIEVE_ALL_USER")]
		public ISingleResult<SP_pRETRIEVE_ALL_USERResult> SP_pRETRIEVE_ALL_USER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_USER)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_USER);
			return ((ISingleResult<SP_pRETRIEVE_ALL_USERResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_pRETRIEVE_CUSTOMER")]
		public ISingleResult<SP_pRETRIEVE_CUSTOMERResult> SP_pRETRIEVE_CUSTOMER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string pCUSTOMER_NAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pCUSTOMER_NAME);
			return ((ISingleResult<SP_pRETRIEVE_CUSTOMERResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_pRETRIEVE_RECEIPT")]
		public ISingleResult<SP_pRETRIEVE_RECEIPTResult> SP_pRETRIEVE_RECEIPT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_RECEIPT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_RECEIPT);
			return ((ISingleResult<SP_pRETRIEVE_RECEIPTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_pRETRIEVE_USER")]
		public ISingleResult<SP_pRETRIEVE_USERResult> SP_pRETRIEVE_USER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_USER)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_USER);
			return ((ISingleResult<SP_pRETRIEVE_USERResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_ALL_AREA")]
		public ISingleResult<SP_RETRIEVE_ALL_AREAResult> SP_RETRIEVE_ALL_AREA()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_ALL_AREAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_ALL_CUSTOMER")]
		public ISingleResult<SP_RETRIEVE_ALL_CUSTOMERResult> SP_RETRIEVE_ALL_CUSTOMER()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_ALL_CUSTOMERResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_ALL_PRICE_TAG")]
		public ISingleResult<SP_RETRIEVE_ALL_PRICE_TAGResult> SP_RETRIEVE_ALL_PRICE_TAG()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_ALL_PRICE_TAGResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_ALL_RECEIPT")]
		public ISingleResult<SP_RETRIEVE_ALL_RECEIPTResult> SP_RETRIEVE_ALL_RECEIPT()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_ALL_RECEIPTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_ALL_USER")]
		public ISingleResult<SP_RETRIEVE_ALL_USERResult> SP_RETRIEVE_ALL_USER()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_ALL_USERResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_AREA")]
		public ISingleResult<SP_RETRIEVE_AREAResult> SP_RETRIEVE_AREA()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_AREAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_AUTHENTICATION")]
		public ISingleResult<SP_RETRIEVE_AUTHENTICATIONResult> SP_RETRIEVE_AUTHENTICATION()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_AUTHENTICATIONResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_CUSTOMER")]
		public ISingleResult<SP_RETRIEVE_CUSTOMERResult> SP_RETRIEVE_CUSTOMER()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_CUSTOMERResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_PRICE_TAG")]
		public ISingleResult<SP_RETRIEVE_PRICE_TAGResult> SP_RETRIEVE_PRICE_TAG()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_PRICE_TAGResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_RECEIPT")]
		public ISingleResult<SP_RETRIEVE_RECEIPTResult> SP_RETRIEVE_RECEIPT()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_RECEIPTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_USER")]
		public ISingleResult<SP_RETRIEVE_USERResult> SP_RETRIEVE_USER()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_USERResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_UPDATE_AREA")]
		public int SP_UPDATE_AREA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_AREA, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string pAREA_NAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_AREA, pAREA_NAME);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_UPDATE_AUTHENTICATION")]
		public int SP_UPDATE_AUTHENTICATION([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_USER, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string pUSER_NICKNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string pPASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_AREA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_USER, pUSER_NICKNAME, pPASSWORD, pID_AREA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_UPDATE_CUSTOMER")]
		public int SP_UPDATE_CUSTOMER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_CUSTOMER, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string pCUSTOMER_NAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_CUSTOMER, pCUSTOMER_NAME);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_UPDATE_PRICE_TAG")]
		public int SP_UPDATE_PRICE_TAG([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_PRICE_TAG, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> pTOTAL_PRICE, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string pDESCRIP_PRICE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_PRICE_TAG, pTOTAL_PRICE, pDESCRIP_PRICE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_UPDATE_RECEIPT")]
		public int SP_UPDATE_RECEIPT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_RECEIPT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string pCUSTOMER_NAME, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> pDATE_RECEIPT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pQUANTITY, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> pTOTAL_RECEIPT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_RECEIPT, pCUSTOMER_NAME, pDATE_RECEIPT, pQUANTITY, pTOTAL_RECEIPT);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_UPDATE_USER")]
		public int SP_UPDATE_USER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_USER, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string pUSER_NAME, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_AREA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_USER, pUSER_NAME, pID_AREA);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AREAS")]
	public partial class AREA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_AREA;
		
		private string _AREA_NAME;
		
		private string _AREA_STATE;
		
		private EntitySet<USER> _USERs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_AREAChanging(int value);
    partial void OnID_AREAChanged();
    partial void OnAREA_NAMEChanging(string value);
    partial void OnAREA_NAMEChanged();
    partial void OnAREA_STATEChanging(string value);
    partial void OnAREA_STATEChanged();
    #endregion
		
		public AREA()
		{
			this._USERs = new EntitySet<USER>(new Action<USER>(this.attach_USERs), new Action<USER>(this.detach_USERs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AREA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_AREA
		{
			get
			{
				return this._ID_AREA;
			}
			set
			{
				if ((this._ID_AREA != value))
				{
					this.OnID_AREAChanging(value);
					this.SendPropertyChanging();
					this._ID_AREA = value;
					this.SendPropertyChanged("ID_AREA");
					this.OnID_AREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA_NAME", DbType="VarChar(25)")]
		public string AREA_NAME
		{
			get
			{
				return this._AREA_NAME;
			}
			set
			{
				if ((this._AREA_NAME != value))
				{
					this.OnAREA_NAMEChanging(value);
					this.SendPropertyChanging();
					this._AREA_NAME = value;
					this.SendPropertyChanged("AREA_NAME");
					this.OnAREA_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA_STATE", DbType="VarChar(10)")]
		public string AREA_STATE
		{
			get
			{
				return this._AREA_STATE;
			}
			set
			{
				if ((this._AREA_STATE != value))
				{
					this.OnAREA_STATEChanging(value);
					this.SendPropertyChanging();
					this._AREA_STATE = value;
					this.SendPropertyChanged("AREA_STATE");
					this.OnAREA_STATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AREA_USER", Storage="_USERs", ThisKey="ID_AREA", OtherKey="ID_AREA")]
		public EntitySet<USER> USERs
		{
			get
			{
				return this._USERs;
			}
			set
			{
				this._USERs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_USERs(USER entity)
		{
			this.SendPropertyChanging();
			entity.AREA = this;
		}
		
		private void detach_USERs(USER entity)
		{
			this.SendPropertyChanging();
			entity.AREA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AUTHENTICATIONS")]
	public partial class AUTHENTICATION
	{
		
		private int _ID_USER;
		
		private string _USER_NICKNAME;
		
		private string _PASSWORD;
		
		private int _ID_AREA;
		
		private string _AUTHENTIC_STATE;
		
		public AUTHENTICATION()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NICKNAME", DbType="VarChar(40)")]
		public string USER_NICKNAME
		{
			get
			{
				return this._USER_NICKNAME;
			}
			set
			{
				if ((this._USER_NICKNAME != value))
				{
					this._USER_NICKNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(20)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this._PASSWORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AREA", DbType="Int NOT NULL")]
		public int ID_AREA
		{
			get
			{
				return this._ID_AREA;
			}
			set
			{
				if ((this._ID_AREA != value))
				{
					this._ID_AREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTHENTIC_STATE", DbType="VarChar(10)")]
		public string AUTHENTIC_STATE
		{
			get
			{
				return this._AUTHENTIC_STATE;
			}
			set
			{
				if ((this._AUTHENTIC_STATE != value))
				{
					this._AUTHENTIC_STATE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CUSTOMERS")]
	public partial class CUSTOMER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CUSTOMER;
		
		private string _CUSTOMER_NAME;
		
		private string _CUSTOMER_STATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CUSTOMERChanging(int value);
    partial void OnID_CUSTOMERChanged();
    partial void OnCUSTOMER_NAMEChanging(string value);
    partial void OnCUSTOMER_NAMEChanged();
    partial void OnCUSTOMER_STATEChanging(string value);
    partial void OnCUSTOMER_STATEChanged();
    #endregion
		
		public CUSTOMER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CUSTOMER", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_CUSTOMER
		{
			get
			{
				return this._ID_CUSTOMER;
			}
			set
			{
				if ((this._ID_CUSTOMER != value))
				{
					this.OnID_CUSTOMERChanging(value);
					this.SendPropertyChanging();
					this._ID_CUSTOMER = value;
					this.SendPropertyChanged("ID_CUSTOMER");
					this.OnID_CUSTOMERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(25)")]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this.OnCUSTOMER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_NAME = value;
					this.SendPropertyChanged("CUSTOMER_NAME");
					this.OnCUSTOMER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_STATE", DbType="VarChar(10)")]
		public string CUSTOMER_STATE
		{
			get
			{
				return this._CUSTOMER_STATE;
			}
			set
			{
				if ((this._CUSTOMER_STATE != value))
				{
					this.OnCUSTOMER_STATEChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_STATE = value;
					this.SendPropertyChanged("CUSTOMER_STATE");
					this.OnCUSTOMER_STATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRICE_TAGS")]
	public partial class PRICE_TAG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PRICE_TAG;
		
		private decimal _TOTAL_PRICE;
		
		private string _DESCRIP_PRICE;
		
		private string _PRICE_TAG_STATE;
		
		private EntitySet<RECEIPT> _RECEIPTs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PRICE_TAGChanging(int value);
    partial void OnID_PRICE_TAGChanged();
    partial void OnTOTAL_PRICEChanging(decimal value);
    partial void OnTOTAL_PRICEChanged();
    partial void OnDESCRIP_PRICEChanging(string value);
    partial void OnDESCRIP_PRICEChanged();
    partial void OnPRICE_TAG_STATEChanging(string value);
    partial void OnPRICE_TAG_STATEChanged();
    #endregion
		
		public PRICE_TAG()
		{
			this._RECEIPTs = new EntitySet<RECEIPT>(new Action<RECEIPT>(this.attach_RECEIPTs), new Action<RECEIPT>(this.detach_RECEIPTs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRICE_TAG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_PRICE_TAG
		{
			get
			{
				return this._ID_PRICE_TAG;
			}
			set
			{
				if ((this._ID_PRICE_TAG != value))
				{
					this.OnID_PRICE_TAGChanging(value);
					this.SendPropertyChanging();
					this._ID_PRICE_TAG = value;
					this.SendPropertyChanged("ID_PRICE_TAG");
					this.OnID_PRICE_TAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_PRICE", DbType="Money NOT NULL")]
		public decimal TOTAL_PRICE
		{
			get
			{
				return this._TOTAL_PRICE;
			}
			set
			{
				if ((this._TOTAL_PRICE != value))
				{
					this.OnTOTAL_PRICEChanging(value);
					this.SendPropertyChanging();
					this._TOTAL_PRICE = value;
					this.SendPropertyChanged("TOTAL_PRICE");
					this.OnTOTAL_PRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIP_PRICE", DbType="VarChar(10)")]
		public string DESCRIP_PRICE
		{
			get
			{
				return this._DESCRIP_PRICE;
			}
			set
			{
				if ((this._DESCRIP_PRICE != value))
				{
					this.OnDESCRIP_PRICEChanging(value);
					this.SendPropertyChanging();
					this._DESCRIP_PRICE = value;
					this.SendPropertyChanged("DESCRIP_PRICE");
					this.OnDESCRIP_PRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE_TAG_STATE", DbType="VarChar(10)")]
		public string PRICE_TAG_STATE
		{
			get
			{
				return this._PRICE_TAG_STATE;
			}
			set
			{
				if ((this._PRICE_TAG_STATE != value))
				{
					this.OnPRICE_TAG_STATEChanging(value);
					this.SendPropertyChanging();
					this._PRICE_TAG_STATE = value;
					this.SendPropertyChanged("PRICE_TAG_STATE");
					this.OnPRICE_TAG_STATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRICE_TAG_RECEIPT", Storage="_RECEIPTs", ThisKey="ID_PRICE_TAG", OtherKey="ID_PRICE_TAG")]
		public EntitySet<RECEIPT> RECEIPTs
		{
			get
			{
				return this._RECEIPTs;
			}
			set
			{
				this._RECEIPTs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RECEIPTs(RECEIPT entity)
		{
			this.SendPropertyChanging();
			entity.PRICE_TAG = this;
		}
		
		private void detach_RECEIPTs(RECEIPT entity)
		{
			this.SendPropertyChanging();
			entity.PRICE_TAG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RECEIPTS")]
	public partial class RECEIPT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_RECEIPT;
		
		private string _CUSTOMER_NAME;
		
		private System.DateTime _DATE_RECEIPT;
		
		private int _QUANTITY;
		
		private decimal _TOTAL_RECEIPT;
		
		private int _ID_PRICE_TAG;
		
		private int _ID_USER;
		
		private string _RECEIPT_STATE;
		
		private EntityRef<PRICE_TAG> _PRICE_TAG;
		
		private EntityRef<USER> _USER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_RECEIPTChanging(int value);
    partial void OnID_RECEIPTChanged();
    partial void OnCUSTOMER_NAMEChanging(string value);
    partial void OnCUSTOMER_NAMEChanged();
    partial void OnDATE_RECEIPTChanging(System.DateTime value);
    partial void OnDATE_RECEIPTChanged();
    partial void OnQUANTITYChanging(int value);
    partial void OnQUANTITYChanged();
    partial void OnTOTAL_RECEIPTChanging(decimal value);
    partial void OnTOTAL_RECEIPTChanged();
    partial void OnID_PRICE_TAGChanging(int value);
    partial void OnID_PRICE_TAGChanged();
    partial void OnID_USERChanging(int value);
    partial void OnID_USERChanged();
    partial void OnRECEIPT_STATEChanging(string value);
    partial void OnRECEIPT_STATEChanged();
    #endregion
		
		public RECEIPT()
		{
			this._PRICE_TAG = default(EntityRef<PRICE_TAG>);
			this._USER = default(EntityRef<USER>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_RECEIPT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_RECEIPT
		{
			get
			{
				return this._ID_RECEIPT;
			}
			set
			{
				if ((this._ID_RECEIPT != value))
				{
					this.OnID_RECEIPTChanging(value);
					this.SendPropertyChanging();
					this._ID_RECEIPT = value;
					this.SendPropertyChanged("ID_RECEIPT");
					this.OnID_RECEIPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this.OnCUSTOMER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_NAME = value;
					this.SendPropertyChanged("CUSTOMER_NAME");
					this.OnCUSTOMER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_RECEIPT", DbType="Date NOT NULL")]
		public System.DateTime DATE_RECEIPT
		{
			get
			{
				return this._DATE_RECEIPT;
			}
			set
			{
				if ((this._DATE_RECEIPT != value))
				{
					this.OnDATE_RECEIPTChanging(value);
					this.SendPropertyChanging();
					this._DATE_RECEIPT = value;
					this.SendPropertyChanged("DATE_RECEIPT");
					this.OnDATE_RECEIPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Int NOT NULL")]
		public int QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this.OnQUANTITYChanging(value);
					this.SendPropertyChanging();
					this._QUANTITY = value;
					this.SendPropertyChanged("QUANTITY");
					this.OnQUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_RECEIPT", DbType="Money NOT NULL")]
		public decimal TOTAL_RECEIPT
		{
			get
			{
				return this._TOTAL_RECEIPT;
			}
			set
			{
				if ((this._TOTAL_RECEIPT != value))
				{
					this.OnTOTAL_RECEIPTChanging(value);
					this.SendPropertyChanging();
					this._TOTAL_RECEIPT = value;
					this.SendPropertyChanged("TOTAL_RECEIPT");
					this.OnTOTAL_RECEIPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRICE_TAG", DbType="Int NOT NULL")]
		public int ID_PRICE_TAG
		{
			get
			{
				return this._ID_PRICE_TAG;
			}
			set
			{
				if ((this._ID_PRICE_TAG != value))
				{
					if (this._PRICE_TAG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PRICE_TAGChanging(value);
					this.SendPropertyChanging();
					this._ID_PRICE_TAG = value;
					this.SendPropertyChanged("ID_PRICE_TAG");
					this.OnID_PRICE_TAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					if (this._USER.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_USERChanging(value);
					this.SendPropertyChanging();
					this._ID_USER = value;
					this.SendPropertyChanged("ID_USER");
					this.OnID_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECEIPT_STATE", DbType="VarChar(10)")]
		public string RECEIPT_STATE
		{
			get
			{
				return this._RECEIPT_STATE;
			}
			set
			{
				if ((this._RECEIPT_STATE != value))
				{
					this.OnRECEIPT_STATEChanging(value);
					this.SendPropertyChanging();
					this._RECEIPT_STATE = value;
					this.SendPropertyChanged("RECEIPT_STATE");
					this.OnRECEIPT_STATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRICE_TAG_RECEIPT", Storage="_PRICE_TAG", ThisKey="ID_PRICE_TAG", OtherKey="ID_PRICE_TAG", IsForeignKey=true)]
		public PRICE_TAG PRICE_TAG
		{
			get
			{
				return this._PRICE_TAG.Entity;
			}
			set
			{
				PRICE_TAG previousValue = this._PRICE_TAG.Entity;
				if (((previousValue != value) 
							|| (this._PRICE_TAG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PRICE_TAG.Entity = null;
						previousValue.RECEIPTs.Remove(this);
					}
					this._PRICE_TAG.Entity = value;
					if ((value != null))
					{
						value.RECEIPTs.Add(this);
						this._ID_PRICE_TAG = value.ID_PRICE_TAG;
					}
					else
					{
						this._ID_PRICE_TAG = default(int);
					}
					this.SendPropertyChanged("PRICE_TAG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USER_RECEIPT", Storage="_USER", ThisKey="ID_USER", OtherKey="ID_USER", IsForeignKey=true)]
		public USER USER
		{
			get
			{
				return this._USER.Entity;
			}
			set
			{
				USER previousValue = this._USER.Entity;
				if (((previousValue != value) 
							|| (this._USER.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._USER.Entity = null;
						previousValue.RECEIPTs.Remove(this);
					}
					this._USER.Entity = value;
					if ((value != null))
					{
						value.RECEIPTs.Add(this);
						this._ID_USER = value.ID_USER;
					}
					else
					{
						this._ID_USER = default(int);
					}
					this.SendPropertyChanged("USER");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USERS")]
	public partial class USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_USER;
		
		private string _USER_NAMEX;
		
		private int _ID_AREA;
		
		private string _USER_STATE;
		
		private EntitySet<RECEIPT> _RECEIPTs;
		
		private EntityRef<AREA> _AREA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_USERChanging(int value);
    partial void OnID_USERChanged();
    partial void OnUSER_NAMEXChanging(string value);
    partial void OnUSER_NAMEXChanged();
    partial void OnID_AREAChanging(int value);
    partial void OnID_AREAChanged();
    partial void OnUSER_STATEChanging(string value);
    partial void OnUSER_STATEChanged();
    #endregion
		
		public USER()
		{
			this._RECEIPTs = new EntitySet<RECEIPT>(new Action<RECEIPT>(this.attach_RECEIPTs), new Action<RECEIPT>(this.detach_RECEIPTs));
			this._AREA = default(EntityRef<AREA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this.OnID_USERChanging(value);
					this.SendPropertyChanging();
					this._ID_USER = value;
					this.SendPropertyChanged("ID_USER");
					this.OnID_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NAMEX", DbType="VarChar(25)")]
		public string USER_NAMEX
		{
			get
			{
				return this._USER_NAMEX;
			}
			set
			{
				if ((this._USER_NAMEX != value))
				{
					this.OnUSER_NAMEXChanging(value);
					this.SendPropertyChanging();
					this._USER_NAMEX = value;
					this.SendPropertyChanged("USER_NAMEX");
					this.OnUSER_NAMEXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AREA", DbType="Int NOT NULL")]
		public int ID_AREA
		{
			get
			{
				return this._ID_AREA;
			}
			set
			{
				if ((this._ID_AREA != value))
				{
					if (this._AREA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_AREAChanging(value);
					this.SendPropertyChanging();
					this._ID_AREA = value;
					this.SendPropertyChanged("ID_AREA");
					this.OnID_AREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_STATE", DbType="VarChar(10)")]
		public string USER_STATE
		{
			get
			{
				return this._USER_STATE;
			}
			set
			{
				if ((this._USER_STATE != value))
				{
					this.OnUSER_STATEChanging(value);
					this.SendPropertyChanging();
					this._USER_STATE = value;
					this.SendPropertyChanged("USER_STATE");
					this.OnUSER_STATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USER_RECEIPT", Storage="_RECEIPTs", ThisKey="ID_USER", OtherKey="ID_USER")]
		public EntitySet<RECEIPT> RECEIPTs
		{
			get
			{
				return this._RECEIPTs;
			}
			set
			{
				this._RECEIPTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AREA_USER", Storage="_AREA", ThisKey="ID_AREA", OtherKey="ID_AREA", IsForeignKey=true)]
		public AREA AREA
		{
			get
			{
				return this._AREA.Entity;
			}
			set
			{
				AREA previousValue = this._AREA.Entity;
				if (((previousValue != value) 
							|| (this._AREA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AREA.Entity = null;
						previousValue.USERs.Remove(this);
					}
					this._AREA.Entity = value;
					if ((value != null))
					{
						value.USERs.Add(this);
						this._ID_AREA = value.ID_AREA;
					}
					else
					{
						this._ID_AREA = default(int);
					}
					this.SendPropertyChanged("AREA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RECEIPTs(RECEIPT entity)
		{
			this.SendPropertyChanging();
			entity.USER = this;
		}
		
		private void detach_RECEIPTs(RECEIPT entity)
		{
			this.SendPropertyChanging();
			entity.USER = null;
		}
	}
	
	public partial class SP_pRETRIEVE_ALL_CUSTOMERResult
	{
		
		private int _ID_CUSTOMER;
		
		private string _CUSTOMER_NAME;
		
		private string _CUSTOMER_STATE;
		
		public SP_pRETRIEVE_ALL_CUSTOMERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CUSTOMER", DbType="Int NOT NULL")]
		public int ID_CUSTOMER
		{
			get
			{
				return this._ID_CUSTOMER;
			}
			set
			{
				if ((this._ID_CUSTOMER != value))
				{
					this._ID_CUSTOMER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(25)")]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this._CUSTOMER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_STATE", DbType="VarChar(10)")]
		public string CUSTOMER_STATE
		{
			get
			{
				return this._CUSTOMER_STATE;
			}
			set
			{
				if ((this._CUSTOMER_STATE != value))
				{
					this._CUSTOMER_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_pRETRIEVE_ALL_RECEIPTResult
	{
		
		private int _ID_RECEIPT;
		
		private string _CUSTOMER_NAME;
		
		private System.DateTime _DATE_RECEIPT;
		
		private int _QUANTITY;
		
		private decimal _TOTAL_RECEIPT;
		
		private int _ID_PRICE_TAG;
		
		private int _ID_USER;
		
		public SP_pRETRIEVE_ALL_RECEIPTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_RECEIPT", DbType="Int NOT NULL")]
		public int ID_RECEIPT
		{
			get
			{
				return this._ID_RECEIPT;
			}
			set
			{
				if ((this._ID_RECEIPT != value))
				{
					this._ID_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this._CUSTOMER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_RECEIPT", DbType="Date NOT NULL")]
		public System.DateTime DATE_RECEIPT
		{
			get
			{
				return this._DATE_RECEIPT;
			}
			set
			{
				if ((this._DATE_RECEIPT != value))
				{
					this._DATE_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Int NOT NULL")]
		public int QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this._QUANTITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_RECEIPT", DbType="Money NOT NULL")]
		public decimal TOTAL_RECEIPT
		{
			get
			{
				return this._TOTAL_RECEIPT;
			}
			set
			{
				if ((this._TOTAL_RECEIPT != value))
				{
					this._TOTAL_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRICE_TAG", DbType="Int NOT NULL")]
		public int ID_PRICE_TAG
		{
			get
			{
				return this._ID_PRICE_TAG;
			}
			set
			{
				if ((this._ID_PRICE_TAG != value))
				{
					this._ID_PRICE_TAG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
	}
	
	public partial class SP_pRETRIEVE_ALL_USERResult
	{
		
		private int _ID_USER;
		
		private string _USER_NAMEX;
		
		private int _ID_AREA;
		
		private string _USER_STATE;
		
		public SP_pRETRIEVE_ALL_USERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NAMEX", DbType="VarChar(25)")]
		public string USER_NAMEX
		{
			get
			{
				return this._USER_NAMEX;
			}
			set
			{
				if ((this._USER_NAMEX != value))
				{
					this._USER_NAMEX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AREA", DbType="Int NOT NULL")]
		public int ID_AREA
		{
			get
			{
				return this._ID_AREA;
			}
			set
			{
				if ((this._ID_AREA != value))
				{
					this._ID_AREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_STATE", DbType="VarChar(10)")]
		public string USER_STATE
		{
			get
			{
				return this._USER_STATE;
			}
			set
			{
				if ((this._USER_STATE != value))
				{
					this._USER_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_pRETRIEVE_CUSTOMERResult
	{
		
		private int _ID_CUSTOMER;
		
		private string _CUSTOMER_NAME;
		
		private string _CUSTOMER_STATE;
		
		public SP_pRETRIEVE_CUSTOMERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CUSTOMER", DbType="Int NOT NULL")]
		public int ID_CUSTOMER
		{
			get
			{
				return this._ID_CUSTOMER;
			}
			set
			{
				if ((this._ID_CUSTOMER != value))
				{
					this._ID_CUSTOMER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(25)")]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this._CUSTOMER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_STATE", DbType="VarChar(10)")]
		public string CUSTOMER_STATE
		{
			get
			{
				return this._CUSTOMER_STATE;
			}
			set
			{
				if ((this._CUSTOMER_STATE != value))
				{
					this._CUSTOMER_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_pRETRIEVE_RECEIPTResult
	{
		
		private int _ID_RECEIPT;
		
		private string _CUSTOMER_NAME;
		
		private System.DateTime _DATE_RECEIPT;
		
		private int _QUANTITY;
		
		private decimal _TOTAL_RECEIPT;
		
		private int _ID_PRICE_TAG;
		
		private int _ID_USER;
		
		public SP_pRETRIEVE_RECEIPTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_RECEIPT", DbType="Int NOT NULL")]
		public int ID_RECEIPT
		{
			get
			{
				return this._ID_RECEIPT;
			}
			set
			{
				if ((this._ID_RECEIPT != value))
				{
					this._ID_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this._CUSTOMER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_RECEIPT", DbType="Date NOT NULL")]
		public System.DateTime DATE_RECEIPT
		{
			get
			{
				return this._DATE_RECEIPT;
			}
			set
			{
				if ((this._DATE_RECEIPT != value))
				{
					this._DATE_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Int NOT NULL")]
		public int QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this._QUANTITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_RECEIPT", DbType="Money NOT NULL")]
		public decimal TOTAL_RECEIPT
		{
			get
			{
				return this._TOTAL_RECEIPT;
			}
			set
			{
				if ((this._TOTAL_RECEIPT != value))
				{
					this._TOTAL_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRICE_TAG", DbType="Int NOT NULL")]
		public int ID_PRICE_TAG
		{
			get
			{
				return this._ID_PRICE_TAG;
			}
			set
			{
				if ((this._ID_PRICE_TAG != value))
				{
					this._ID_PRICE_TAG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
	}
	
	public partial class SP_pRETRIEVE_USERResult
	{
		
		private int _ID_USER;
		
		private string _USER_NAMEX;
		
		private int _ID_AREA;
		
		private string _USER_STATE;
		
		public SP_pRETRIEVE_USERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NAMEX", DbType="VarChar(25)")]
		public string USER_NAMEX
		{
			get
			{
				return this._USER_NAMEX;
			}
			set
			{
				if ((this._USER_NAMEX != value))
				{
					this._USER_NAMEX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AREA", DbType="Int NOT NULL")]
		public int ID_AREA
		{
			get
			{
				return this._ID_AREA;
			}
			set
			{
				if ((this._ID_AREA != value))
				{
					this._ID_AREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_STATE", DbType="VarChar(10)")]
		public string USER_STATE
		{
			get
			{
				return this._USER_STATE;
			}
			set
			{
				if ((this._USER_STATE != value))
				{
					this._USER_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_ALL_AREAResult
	{
		
		private int _ID_AREA;
		
		private string _AREA_NAME;
		
		private string _AREA_STATE;
		
		public SP_RETRIEVE_ALL_AREAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AREA", DbType="Int NOT NULL")]
		public int ID_AREA
		{
			get
			{
				return this._ID_AREA;
			}
			set
			{
				if ((this._ID_AREA != value))
				{
					this._ID_AREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA_NAME", DbType="VarChar(25)")]
		public string AREA_NAME
		{
			get
			{
				return this._AREA_NAME;
			}
			set
			{
				if ((this._AREA_NAME != value))
				{
					this._AREA_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA_STATE", DbType="VarChar(10)")]
		public string AREA_STATE
		{
			get
			{
				return this._AREA_STATE;
			}
			set
			{
				if ((this._AREA_STATE != value))
				{
					this._AREA_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_ALL_CUSTOMERResult
	{
		
		private int _ID_CUSTOMER;
		
		private string _CUSTOMER_NAME;
		
		private string _CUSTOMER_STATE;
		
		public SP_RETRIEVE_ALL_CUSTOMERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CUSTOMER", DbType="Int NOT NULL")]
		public int ID_CUSTOMER
		{
			get
			{
				return this._ID_CUSTOMER;
			}
			set
			{
				if ((this._ID_CUSTOMER != value))
				{
					this._ID_CUSTOMER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(25)")]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this._CUSTOMER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_STATE", DbType="VarChar(10)")]
		public string CUSTOMER_STATE
		{
			get
			{
				return this._CUSTOMER_STATE;
			}
			set
			{
				if ((this._CUSTOMER_STATE != value))
				{
					this._CUSTOMER_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_ALL_PRICE_TAGResult
	{
		
		private int _ID_PRICE_TAG;
		
		private decimal _TOTAL_PRICE;
		
		private string _DESCRIP_PRICE;
		
		private string _PRICE_TAG_STATE;
		
		public SP_RETRIEVE_ALL_PRICE_TAGResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRICE_TAG", DbType="Int NOT NULL")]
		public int ID_PRICE_TAG
		{
			get
			{
				return this._ID_PRICE_TAG;
			}
			set
			{
				if ((this._ID_PRICE_TAG != value))
				{
					this._ID_PRICE_TAG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_PRICE", DbType="Money NOT NULL")]
		public decimal TOTAL_PRICE
		{
			get
			{
				return this._TOTAL_PRICE;
			}
			set
			{
				if ((this._TOTAL_PRICE != value))
				{
					this._TOTAL_PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIP_PRICE", DbType="VarChar(10)")]
		public string DESCRIP_PRICE
		{
			get
			{
				return this._DESCRIP_PRICE;
			}
			set
			{
				if ((this._DESCRIP_PRICE != value))
				{
					this._DESCRIP_PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE_TAG_STATE", DbType="VarChar(10)")]
		public string PRICE_TAG_STATE
		{
			get
			{
				return this._PRICE_TAG_STATE;
			}
			set
			{
				if ((this._PRICE_TAG_STATE != value))
				{
					this._PRICE_TAG_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_ALL_RECEIPTResult
	{
		
		private int _ID_RECEIPT;
		
		private string _CUSTOMER_NAME;
		
		private System.DateTime _DATE_RECEIPT;
		
		private int _QUANTITY;
		
		private decimal _TOTAL_RECEIPT;
		
		private int _ID_PRICE_TAG;
		
		private int _ID_USER;
		
		public SP_RETRIEVE_ALL_RECEIPTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_RECEIPT", DbType="Int NOT NULL")]
		public int ID_RECEIPT
		{
			get
			{
				return this._ID_RECEIPT;
			}
			set
			{
				if ((this._ID_RECEIPT != value))
				{
					this._ID_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this._CUSTOMER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_RECEIPT", DbType="Date NOT NULL")]
		public System.DateTime DATE_RECEIPT
		{
			get
			{
				return this._DATE_RECEIPT;
			}
			set
			{
				if ((this._DATE_RECEIPT != value))
				{
					this._DATE_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Int NOT NULL")]
		public int QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this._QUANTITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_RECEIPT", DbType="Money NOT NULL")]
		public decimal TOTAL_RECEIPT
		{
			get
			{
				return this._TOTAL_RECEIPT;
			}
			set
			{
				if ((this._TOTAL_RECEIPT != value))
				{
					this._TOTAL_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRICE_TAG", DbType="Int NOT NULL")]
		public int ID_PRICE_TAG
		{
			get
			{
				return this._ID_PRICE_TAG;
			}
			set
			{
				if ((this._ID_PRICE_TAG != value))
				{
					this._ID_PRICE_TAG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_ALL_USERResult
	{
		
		private int _ID_USER;
		
		private string _USER_NAMEX;
		
		private int _ID_AREA;
		
		private string _USER_STATE;
		
		public SP_RETRIEVE_ALL_USERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NAMEX", DbType="VarChar(25)")]
		public string USER_NAMEX
		{
			get
			{
				return this._USER_NAMEX;
			}
			set
			{
				if ((this._USER_NAMEX != value))
				{
					this._USER_NAMEX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AREA", DbType="Int NOT NULL")]
		public int ID_AREA
		{
			get
			{
				return this._ID_AREA;
			}
			set
			{
				if ((this._ID_AREA != value))
				{
					this._ID_AREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_STATE", DbType="VarChar(10)")]
		public string USER_STATE
		{
			get
			{
				return this._USER_STATE;
			}
			set
			{
				if ((this._USER_STATE != value))
				{
					this._USER_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_AREAResult
	{
		
		private int _ID_AREA;
		
		private string _AREA_NAME;
		
		private string _AREA_STATE;
		
		public SP_RETRIEVE_AREAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AREA", DbType="Int NOT NULL")]
		public int ID_AREA
		{
			get
			{
				return this._ID_AREA;
			}
			set
			{
				if ((this._ID_AREA != value))
				{
					this._ID_AREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA_NAME", DbType="VarChar(25)")]
		public string AREA_NAME
		{
			get
			{
				return this._AREA_NAME;
			}
			set
			{
				if ((this._AREA_NAME != value))
				{
					this._AREA_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA_STATE", DbType="VarChar(10)")]
		public string AREA_STATE
		{
			get
			{
				return this._AREA_STATE;
			}
			set
			{
				if ((this._AREA_STATE != value))
				{
					this._AREA_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_AUTHENTICATIONResult
	{
		
		private int _ID_USER;
		
		private string _USER_NICKNAME;
		
		private string _PASSWORD;
		
		private int _ID_AREA;
		
		private string _AUTHENTIC_STATE;
		
		public SP_RETRIEVE_AUTHENTICATIONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NICKNAME", DbType="VarChar(40)")]
		public string USER_NICKNAME
		{
			get
			{
				return this._USER_NICKNAME;
			}
			set
			{
				if ((this._USER_NICKNAME != value))
				{
					this._USER_NICKNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(20)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this._PASSWORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AREA", DbType="Int NOT NULL")]
		public int ID_AREA
		{
			get
			{
				return this._ID_AREA;
			}
			set
			{
				if ((this._ID_AREA != value))
				{
					this._ID_AREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTHENTIC_STATE", DbType="VarChar(10)")]
		public string AUTHENTIC_STATE
		{
			get
			{
				return this._AUTHENTIC_STATE;
			}
			set
			{
				if ((this._AUTHENTIC_STATE != value))
				{
					this._AUTHENTIC_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_CUSTOMERResult
	{
		
		private int _ID_CUSTOMER;
		
		private string _CUSTOMER_NAME;
		
		private string _CUSTOMER_STATE;
		
		public SP_RETRIEVE_CUSTOMERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CUSTOMER", DbType="Int NOT NULL")]
		public int ID_CUSTOMER
		{
			get
			{
				return this._ID_CUSTOMER;
			}
			set
			{
				if ((this._ID_CUSTOMER != value))
				{
					this._ID_CUSTOMER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(25)")]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this._CUSTOMER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_STATE", DbType="VarChar(10)")]
		public string CUSTOMER_STATE
		{
			get
			{
				return this._CUSTOMER_STATE;
			}
			set
			{
				if ((this._CUSTOMER_STATE != value))
				{
					this._CUSTOMER_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_PRICE_TAGResult
	{
		
		private int _ID_PRICE_TAG;
		
		private decimal _TOTAL_PRICE;
		
		private string _DESCRIP_PRICE;
		
		public SP_RETRIEVE_PRICE_TAGResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRICE_TAG", DbType="Int NOT NULL")]
		public int ID_PRICE_TAG
		{
			get
			{
				return this._ID_PRICE_TAG;
			}
			set
			{
				if ((this._ID_PRICE_TAG != value))
				{
					this._ID_PRICE_TAG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_PRICE", DbType="Money NOT NULL")]
		public decimal TOTAL_PRICE
		{
			get
			{
				return this._TOTAL_PRICE;
			}
			set
			{
				if ((this._TOTAL_PRICE != value))
				{
					this._TOTAL_PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIP_PRICE", DbType="VarChar(10)")]
		public string DESCRIP_PRICE
		{
			get
			{
				return this._DESCRIP_PRICE;
			}
			set
			{
				if ((this._DESCRIP_PRICE != value))
				{
					this._DESCRIP_PRICE = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_RECEIPTResult
	{
		
		private int _ID_RECEIPT;
		
		private string _CUSTOMER_NAME;
		
		private System.DateTime _DATE_RECEIPT;
		
		private int _QUANTITY;
		
		private decimal _TOTAL_RECEIPT;
		
		private int _ID_PRICE_TAG;
		
		private int _ID_USER;
		
		public SP_RETRIEVE_RECEIPTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_RECEIPT", DbType="Int NOT NULL")]
		public int ID_RECEIPT
		{
			get
			{
				return this._ID_RECEIPT;
			}
			set
			{
				if ((this._ID_RECEIPT != value))
				{
					this._ID_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this._CUSTOMER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_RECEIPT", DbType="Date NOT NULL")]
		public System.DateTime DATE_RECEIPT
		{
			get
			{
				return this._DATE_RECEIPT;
			}
			set
			{
				if ((this._DATE_RECEIPT != value))
				{
					this._DATE_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Int NOT NULL")]
		public int QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this._QUANTITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_RECEIPT", DbType="Money NOT NULL")]
		public decimal TOTAL_RECEIPT
		{
			get
			{
				return this._TOTAL_RECEIPT;
			}
			set
			{
				if ((this._TOTAL_RECEIPT != value))
				{
					this._TOTAL_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRICE_TAG", DbType="Int NOT NULL")]
		public int ID_PRICE_TAG
		{
			get
			{
				return this._ID_PRICE_TAG;
			}
			set
			{
				if ((this._ID_PRICE_TAG != value))
				{
					this._ID_PRICE_TAG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_USERResult
	{
		
		private int _ID_USER;
		
		private string _USER_NAMEX;
		
		private int _ID_AREA;
		
		private string _USER_STATE;
		
		public SP_RETRIEVE_USERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NAMEX", DbType="VarChar(25)")]
		public string USER_NAMEX
		{
			get
			{
				return this._USER_NAMEX;
			}
			set
			{
				if ((this._USER_NAMEX != value))
				{
					this._USER_NAMEX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AREA", DbType="Int NOT NULL")]
		public int ID_AREA
		{
			get
			{
				return this._ID_AREA;
			}
			set
			{
				if ((this._ID_AREA != value))
				{
					this._ID_AREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_STATE", DbType="VarChar(10)")]
		public string USER_STATE
		{
			get
			{
				return this._USER_STATE;
			}
			set
			{
				if ((this._USER_STATE != value))
				{
					this._USER_STATE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
