#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlApp.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbo.Receipts")]
	public partial class ContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBLAreas(TBLAreas instance);
    partial void UpdateTBLAreas(TBLAreas instance);
    partial void DeleteTBLAreas(TBLAreas instance);
    partial void InsertTBLCustomers(TBLCustomers instance);
    partial void UpdateTBLCustomers(TBLCustomers instance);
    partial void DeleteTBLCustomers(TBLCustomers instance);
    partial void InsertTBLPrice_tags(TBLPrice_tags instance);
    partial void UpdateTBLPrice_tags(TBLPrice_tags instance);
    partial void DeleteTBLPrice_tags(TBLPrice_tags instance);
    partial void InsertTBLReceipts(TBLReceipts instance);
    partial void UpdateTBLReceipts(TBLReceipts instance);
    partial void DeleteTBLReceipts(TBLReceipts instance);
    partial void InsertTBLUsers(TBLUsers instance);
    partial void UpdateTBLUsers(TBLUsers instance);
    partial void DeleteTBLUsers(TBLUsers instance);
    #endregion
		
		public ContextDataContext() : 
				base(global::ControlApp.DataAccess.Properties.Settings.Default.dbo_ReceiptsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBLAreas> TBLAreas
		{
			get
			{
				return this.GetTable<TBLAreas>();
			}
		}
		
		public System.Data.Linq.Table<TBLAuthenticacios> TBLAuthenticacios
		{
			get
			{
				return this.GetTable<TBLAuthenticacios>();
			}
		}
		
		public System.Data.Linq.Table<TBLCustomers> TBLCustomers
		{
			get
			{
				return this.GetTable<TBLCustomers>();
			}
		}
		
		public System.Data.Linq.Table<TBLPrice_tags> TBLPrice_tags
		{
			get
			{
				return this.GetTable<TBLPrice_tags>();
			}
		}
		
		public System.Data.Linq.Table<TBLReceipts> TBLReceipts
		{
			get
			{
				return this.GetTable<TBLReceipts>();
			}
		}
		
		public System.Data.Linq.Table<TBLUsers> TBLUsers
		{
			get
			{
				return this.GetTable<TBLUsers>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CREATE_AREA")]
		public int SP_CREATE_AREA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string pAREA_NAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pAREA_NAME);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CREATE_AUTHENTICATION")]
		public int SP_CREATE_AUTHENTICATION([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_USER, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string pUSER_NICKNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string pPASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_AREA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_USER, pUSER_NICKNAME, pPASSWORD, pID_AREA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CREATE_CUSTOMER")]
		public int SP_CREATE_CUSTOMER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_CUSTOMER, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string pCUSTOMER_NAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_CUSTOMER, pCUSTOMER_NAME);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CREATE_PRICE_TAG")]
		public int SP_CREATE_PRICE_TAG([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> pTOTAL_PRICE, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string pDESCRIP_PRICE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pTOTAL_PRICE, pDESCRIP_PRICE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CREATE_RECEIPT")]
		public int SP_CREATE_RECEIPT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string pCUSTOMER_NAME, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> pDATE_RECEIPT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pQUANTITY, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> pTOTAL_RECEIPT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_PRICE_TAG, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_USER)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pCUSTOMER_NAME, pDATE_RECEIPT, pQUANTITY, pTOTAL_RECEIPT, pID_PRICE_TAG, pID_USER);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CREATE_USER")]
		public int SP_CREATE_USER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_USER, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string pUSER_NAME, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_AREA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_USER, pUSER_NAME, pID_AREA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DELETE_AREA")]
		public int SP_DELETE_AREA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_AREA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_AREA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DELETE_AUTHENTICATION")]
		public int SP_DELETE_AUTHENTICATION([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_USER)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_USER);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DELETE_CUSTOMER")]
		public int SP_DELETE_CUSTOMER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_CUSTOMER)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_CUSTOMER);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DELETE_PRICE_TAG")]
		public int SP_DELETE_PRICE_TAG([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_PRICE_TAG)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_PRICE_TAG);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DELETE_RECEIPT")]
		public int SP_DELETE_RECEIPT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_RECEIPT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_RECEIPT);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DELETE_USER")]
		public int SP_DELETE_USER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_USER)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_USER);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_pRETRIEVE_ALL_CUSTOMER")]
		public ISingleResult<SP_pRETRIEVE_ALL_CUSTOMERResult> SP_pRETRIEVE_ALL_CUSTOMER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string pCUSTOMER_NAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pCUSTOMER_NAME);
			return ((ISingleResult<SP_pRETRIEVE_ALL_CUSTOMERResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_pRETRIEVE_ALL_RECEIPT")]
		public ISingleResult<SP_pRETRIEVE_ALL_RECEIPTResult> SP_pRETRIEVE_ALL_RECEIPT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_RECEIPT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_RECEIPT);
			return ((ISingleResult<SP_pRETRIEVE_ALL_RECEIPTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_pRETRIEVE_ALL_USER")]
		public ISingleResult<SP_pRETRIEVE_ALL_USERResult> SP_pRETRIEVE_ALL_USER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_USER)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_USER);
			return ((ISingleResult<SP_pRETRIEVE_ALL_USERResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_pRETRIEVE_CUSTOMER")]
		public ISingleResult<SP_pRETRIEVE_CUSTOMERResult> SP_pRETRIEVE_CUSTOMER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string pCUSTOMER_NAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pCUSTOMER_NAME);
			return ((ISingleResult<SP_pRETRIEVE_CUSTOMERResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_pRETRIEVE_RECEIPT")]
		public ISingleResult<SP_pRETRIEVE_RECEIPTResult> SP_pRETRIEVE_RECEIPT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_RECEIPT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_RECEIPT);
			return ((ISingleResult<SP_pRETRIEVE_RECEIPTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_pRETRIEVE_USER")]
		public ISingleResult<SP_pRETRIEVE_USERResult> SP_pRETRIEVE_USER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_USER)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_USER);
			return ((ISingleResult<SP_pRETRIEVE_USERResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_ALL_AREA")]
		public ISingleResult<SP_RETRIEVE_ALL_AREAResult> SP_RETRIEVE_ALL_AREA()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_ALL_AREAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_ALL_CUSTOMER")]
		public ISingleResult<SP_RETRIEVE_ALL_CUSTOMERResult> SP_RETRIEVE_ALL_CUSTOMER()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_ALL_CUSTOMERResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_ALL_PRICE_TAG")]
		public ISingleResult<SP_RETRIEVE_ALL_PRICE_TAGResult> SP_RETRIEVE_ALL_PRICE_TAG()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_ALL_PRICE_TAGResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_ALL_RECEIPT")]
		public ISingleResult<SP_RETRIEVE_ALL_RECEIPTResult> SP_RETRIEVE_ALL_RECEIPT()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_ALL_RECEIPTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_ALL_USER")]
		public ISingleResult<SP_RETRIEVE_ALL_USERResult> SP_RETRIEVE_ALL_USER()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_ALL_USERResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_AREA")]
		public ISingleResult<SP_RETRIEVE_AREAResult> SP_RETRIEVE_AREA()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_AREAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_AUTHENTICATION")]
		public ISingleResult<SP_RETRIEVE_AUTHENTICATIONResult> SP_RETRIEVE_AUTHENTICATION()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_AUTHENTICATIONResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_CUSTOMER")]
		public ISingleResult<SP_RETRIEVE_CUSTOMERResult> SP_RETRIEVE_CUSTOMER()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_CUSTOMERResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_PRICE_TAG")]
		public ISingleResult<SP_RETRIEVE_PRICE_TAGResult> SP_RETRIEVE_PRICE_TAG()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_PRICE_TAGResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_RECEIPT")]
		public ISingleResult<SP_RETRIEVE_RECEIPTResult> SP_RETRIEVE_RECEIPT()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_RECEIPTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RETRIEVE_USER")]
		public ISingleResult<SP_RETRIEVE_USERResult> SP_RETRIEVE_USER()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_RETRIEVE_USERResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_UPDATE_AREA")]
		public int SP_UPDATE_AREA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_AREA, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string pAREA_NAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_AREA, pAREA_NAME);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_UPDATE_AUTHENTICATION")]
		public int SP_UPDATE_AUTHENTICATION([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_USER, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string pUSER_NICKNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string pPASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_AREA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_USER, pUSER_NICKNAME, pPASSWORD, pID_AREA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_UPDATE_CUSTOMER")]
		public int SP_UPDATE_CUSTOMER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_CUSTOMER, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string pCUSTOMER_NAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_CUSTOMER, pCUSTOMER_NAME);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_UPDATE_PRICE_TAG")]
		public int SP_UPDATE_PRICE_TAG([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_PRICE_TAG, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> pTOTAL_PRICE, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string pDESCRIP_PRICE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_PRICE_TAG, pTOTAL_PRICE, pDESCRIP_PRICE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_UPDATE_RECEIPT")]
		public int SP_UPDATE_RECEIPT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_RECEIPT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string pCUSTOMER_NAME, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> pDATE_RECEIPT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pQUANTITY, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> pTOTAL_RECEIPT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_RECEIPT, pCUSTOMER_NAME, pDATE_RECEIPT, pQUANTITY, pTOTAL_RECEIPT);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_UPDATE_USER")]
		public int SP_UPDATE_USER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_USER, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string pUSER_NAME, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pID_AREA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID_USER, pUSER_NAME, pID_AREA);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AREAS")]
	public partial class TBLAreas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_AREA;
		
		private string _AREA_NAME;
		
		private string _AREA_STATE;
		
		private EntitySet<TBLUsers> _TBLUsers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_AREAChanging(int value);
    partial void OnID_AREAChanged();
    partial void OnAREA_NAMEChanging(string value);
    partial void OnAREA_NAMEChanged();
    partial void OnAREA_STATEChanging(string value);
    partial void OnAREA_STATEChanged();
    #endregion
		
		public TBLAreas()
		{
			this._TBLUsers = new EntitySet<TBLUsers>(new Action<TBLUsers>(this.attach_TBLUsers), new Action<TBLUsers>(this.detach_TBLUsers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AREA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_AREA
		{
			get
			{
				return this._ID_AREA;
			}
			set
			{
				if ((this._ID_AREA != value))
				{
					this.OnID_AREAChanging(value);
					this.SendPropertyChanging();
					this._ID_AREA = value;
					this.SendPropertyChanged("ID_AREA");
					this.OnID_AREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA_NAME", DbType="VarChar(25)")]
		public string AREA_NAME
		{
			get
			{
				return this._AREA_NAME;
			}
			set
			{
				if ((this._AREA_NAME != value))
				{
					this.OnAREA_NAMEChanging(value);
					this.SendPropertyChanging();
					this._AREA_NAME = value;
					this.SendPropertyChanged("AREA_NAME");
					this.OnAREA_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA_STATE", DbType="VarChar(10)")]
		public string AREA_STATE
		{
			get
			{
				return this._AREA_STATE;
			}
			set
			{
				if ((this._AREA_STATE != value))
				{
					this.OnAREA_STATEChanging(value);
					this.SendPropertyChanging();
					this._AREA_STATE = value;
					this.SendPropertyChanged("AREA_STATE");
					this.OnAREA_STATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLAreas_TBLUsers", Storage="_TBLUsers", ThisKey="ID_AREA", OtherKey="ID_AREA")]
		public EntitySet<TBLUsers> TBLUsers
		{
			get
			{
				return this._TBLUsers;
			}
			set
			{
				this._TBLUsers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBLUsers(TBLUsers entity)
		{
			this.SendPropertyChanging();
			entity.TBLAreas = this;
		}
		
		private void detach_TBLUsers(TBLUsers entity)
		{
			this.SendPropertyChanging();
			entity.TBLAreas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AUTHENTICATIONS")]
	public partial class TBLAuthenticacios
	{
		
		private int _ID_USER;
		
		private string _USER_NICKNAME;
		
		private string _PASSWORD;
		
		private int _ID_AREA;
		
		private string _AUTHENTIC_STATE;
		
		public TBLAuthenticacios()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NICKNAME", DbType="VarChar(40)")]
		public string USER_NICKNAME
		{
			get
			{
				return this._USER_NICKNAME;
			}
			set
			{
				if ((this._USER_NICKNAME != value))
				{
					this._USER_NICKNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(20)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this._PASSWORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AREA", DbType="Int NOT NULL")]
		public int ID_AREA
		{
			get
			{
				return this._ID_AREA;
			}
			set
			{
				if ((this._ID_AREA != value))
				{
					this._ID_AREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTHENTIC_STATE", DbType="VarChar(10)")]
		public string AUTHENTIC_STATE
		{
			get
			{
				return this._AUTHENTIC_STATE;
			}
			set
			{
				if ((this._AUTHENTIC_STATE != value))
				{
					this._AUTHENTIC_STATE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CUSTOMERS")]
	public partial class TBLCustomers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CUSTOMER;
		
		private string _CUSTOMER_NAME;
		
		private string _CUSTOMER_STATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CUSTOMERChanging(int value);
    partial void OnID_CUSTOMERChanged();
    partial void OnCUSTOMER_NAMEChanging(string value);
    partial void OnCUSTOMER_NAMEChanged();
    partial void OnCUSTOMER_STATEChanging(string value);
    partial void OnCUSTOMER_STATEChanged();
    #endregion
		
		public TBLCustomers()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CUSTOMER", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_CUSTOMER
		{
			get
			{
				return this._ID_CUSTOMER;
			}
			set
			{
				if ((this._ID_CUSTOMER != value))
				{
					this.OnID_CUSTOMERChanging(value);
					this.SendPropertyChanging();
					this._ID_CUSTOMER = value;
					this.SendPropertyChanged("ID_CUSTOMER");
					this.OnID_CUSTOMERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(25)")]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this.OnCUSTOMER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_NAME = value;
					this.SendPropertyChanged("CUSTOMER_NAME");
					this.OnCUSTOMER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_STATE", DbType="VarChar(10)")]
		public string CUSTOMER_STATE
		{
			get
			{
				return this._CUSTOMER_STATE;
			}
			set
			{
				if ((this._CUSTOMER_STATE != value))
				{
					this.OnCUSTOMER_STATEChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_STATE = value;
					this.SendPropertyChanged("CUSTOMER_STATE");
					this.OnCUSTOMER_STATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRICE_TAGS")]
	public partial class TBLPrice_tags : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PRICE_TAG;
		
		private System.Nullable<decimal> _TOTAL_PRICE;
		
		private string _DESCRIP_PRICE;
		
		private string _PRICE_TAG_STATE;
		
		private EntitySet<TBLReceipts> _TBLReceipts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PRICE_TAGChanging(int value);
    partial void OnID_PRICE_TAGChanged();
    partial void OnTOTAL_PRICEChanging(System.Nullable<decimal> value);
    partial void OnTOTAL_PRICEChanged();
    partial void OnDESCRIP_PRICEChanging(string value);
    partial void OnDESCRIP_PRICEChanged();
    partial void OnPRICE_TAG_STATEChanging(string value);
    partial void OnPRICE_TAG_STATEChanged();
    #endregion
		
		public TBLPrice_tags()
		{
			this._TBLReceipts = new EntitySet<TBLReceipts>(new Action<TBLReceipts>(this.attach_TBLReceipts), new Action<TBLReceipts>(this.detach_TBLReceipts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRICE_TAG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_PRICE_TAG
		{
			get
			{
				return this._ID_PRICE_TAG;
			}
			set
			{
				if ((this._ID_PRICE_TAG != value))
				{
					this.OnID_PRICE_TAGChanging(value);
					this.SendPropertyChanging();
					this._ID_PRICE_TAG = value;
					this.SendPropertyChanged("ID_PRICE_TAG");
					this.OnID_PRICE_TAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_PRICE", DbType="Money")]
		public System.Nullable<decimal> TOTAL_PRICE
		{
			get
			{
				return this._TOTAL_PRICE;
			}
			set
			{
				if ((this._TOTAL_PRICE != value))
				{
					this.OnTOTAL_PRICEChanging(value);
					this.SendPropertyChanging();
					this._TOTAL_PRICE = value;
					this.SendPropertyChanged("TOTAL_PRICE");
					this.OnTOTAL_PRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIP_PRICE", DbType="VarChar(10)")]
		public string DESCRIP_PRICE
		{
			get
			{
				return this._DESCRIP_PRICE;
			}
			set
			{
				if ((this._DESCRIP_PRICE != value))
				{
					this.OnDESCRIP_PRICEChanging(value);
					this.SendPropertyChanging();
					this._DESCRIP_PRICE = value;
					this.SendPropertyChanged("DESCRIP_PRICE");
					this.OnDESCRIP_PRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE_TAG_STATE", DbType="VarChar(10)")]
		public string PRICE_TAG_STATE
		{
			get
			{
				return this._PRICE_TAG_STATE;
			}
			set
			{
				if ((this._PRICE_TAG_STATE != value))
				{
					this.OnPRICE_TAG_STATEChanging(value);
					this.SendPropertyChanging();
					this._PRICE_TAG_STATE = value;
					this.SendPropertyChanged("PRICE_TAG_STATE");
					this.OnPRICE_TAG_STATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLPricetags_TBLReceipts", Storage="_TBLReceipts", ThisKey="ID_PRICE_TAG", OtherKey="ID_PRICE_TAG")]
		public EntitySet<TBLReceipts> TBLReceipts
		{
			get
			{
				return this._TBLReceipts;
			}
			set
			{
				this._TBLReceipts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBLReceipts(TBLReceipts entity)
		{
			this.SendPropertyChanging();
			entity.TBLPrice_tags = this;
		}
		
		private void detach_TBLReceipts(TBLReceipts entity)
		{
			this.SendPropertyChanging();
			entity.TBLPrice_tags = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RECEIPTS")]
	public partial class TBLReceipts : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_RECEIPT;
		
		private string _CUSTOMER_NAME;
		
		private System.DateTime _DATE_RECEIPT;
		
		private int _QUANTITY;
		
		private System.Nullable<decimal> _TOTAL_RECEIPT;
		
		private System.Nullable<int> _ID_PRICE_TAG;
		
		private int _ID_USER;
		
		private string _RECEIPT_STATE;
		
		private EntityRef<TBLPrice_tags> _TBLPricetags;
		
		private EntityRef<TBLUsers> _TBLUsers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_RECEIPTChanging(int value);
    partial void OnID_RECEIPTChanged();
    partial void OnCUSTOMER_NAMEChanging(string value);
    partial void OnCUSTOMER_NAMEChanged();
    partial void OnDATE_RECEIPTChanging(System.DateTime value);
    partial void OnDATE_RECEIPTChanged();
    partial void OnQUANTITYChanging(int value);
    partial void OnQUANTITYChanged();
    partial void OnTOTAL_RECEIPTChanging(System.Nullable<decimal> value);
    partial void OnTOTAL_RECEIPTChanged();
    partial void OnID_PRICE_TAGChanging(System.Nullable<int> value);
    partial void OnID_PRICE_TAGChanged();
    partial void OnID_USERChanging(int value);
    partial void OnID_USERChanged();
    partial void OnRECEIPT_STATEChanging(string value);
    partial void OnRECEIPT_STATEChanged();
    #endregion
		
		public TBLReceipts()
		{
			this._TBLPricetags = default(EntityRef<TBLPrice_tags>);
			this._TBLUsers = default(EntityRef<TBLUsers>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_RECEIPT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_RECEIPT
		{
			get
			{
				return this._ID_RECEIPT;
			}
			set
			{
				if ((this._ID_RECEIPT != value))
				{
					this.OnID_RECEIPTChanging(value);
					this.SendPropertyChanging();
					this._ID_RECEIPT = value;
					this.SendPropertyChanged("ID_RECEIPT");
					this.OnID_RECEIPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this.OnCUSTOMER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_NAME = value;
					this.SendPropertyChanged("CUSTOMER_NAME");
					this.OnCUSTOMER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_RECEIPT", DbType="Date NOT NULL")]
		public System.DateTime DATE_RECEIPT
		{
			get
			{
				return this._DATE_RECEIPT;
			}
			set
			{
				if ((this._DATE_RECEIPT != value))
				{
					this.OnDATE_RECEIPTChanging(value);
					this.SendPropertyChanging();
					this._DATE_RECEIPT = value;
					this.SendPropertyChanged("DATE_RECEIPT");
					this.OnDATE_RECEIPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Int NOT NULL")]
		public int QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this.OnQUANTITYChanging(value);
					this.SendPropertyChanging();
					this._QUANTITY = value;
					this.SendPropertyChanged("QUANTITY");
					this.OnQUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_RECEIPT", DbType="Money")]
		public System.Nullable<decimal> TOTAL_RECEIPT
		{
			get
			{
				return this._TOTAL_RECEIPT;
			}
			set
			{
				if ((this._TOTAL_RECEIPT != value))
				{
					this.OnTOTAL_RECEIPTChanging(value);
					this.SendPropertyChanging();
					this._TOTAL_RECEIPT = value;
					this.SendPropertyChanged("TOTAL_RECEIPT");
					this.OnTOTAL_RECEIPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRICE_TAG", DbType="Int")]
		public System.Nullable<int> ID_PRICE_TAG
		{
			get
			{
				return this._ID_PRICE_TAG;
			}
			set
			{
				if ((this._ID_PRICE_TAG != value))
				{
					if (this._TBLPricetags.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PRICE_TAGChanging(value);
					this.SendPropertyChanging();
					this._ID_PRICE_TAG = value;
					this.SendPropertyChanged("ID_PRICE_TAG");
					this.OnID_PRICE_TAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					if (this._TBLUsers.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_USERChanging(value);
					this.SendPropertyChanging();
					this._ID_USER = value;
					this.SendPropertyChanged("ID_USER");
					this.OnID_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECEIPT_STATE", DbType="VarChar(10)")]
		public string RECEIPT_STATE
		{
			get
			{
				return this._RECEIPT_STATE;
			}
			set
			{
				if ((this._RECEIPT_STATE != value))
				{
					this.OnRECEIPT_STATEChanging(value);
					this.SendPropertyChanging();
					this._RECEIPT_STATE = value;
					this.SendPropertyChanged("RECEIPT_STATE");
					this.OnRECEIPT_STATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLPricetags_TBLReceipts", Storage="_TBLPricetags", ThisKey="ID_PRICE_TAG", OtherKey="ID_PRICE_TAG", IsForeignKey=true)]
		public TBLPrice_tags TBLPrice_tags
		{
			get
			{
				return this._TBLPricetags.Entity;
			}
			set
			{
				TBLPrice_tags previousValue = this._TBLPricetags.Entity;
				if (((previousValue != value) 
							|| (this._TBLPricetags.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLPricetags.Entity = null;
						previousValue.TBLReceipts.Remove(this);
					}
					this._TBLPricetags.Entity = value;
					if ((value != null))
					{
						value.TBLReceipts.Add(this);
						this._ID_PRICE_TAG = value.ID_PRICE_TAG;
					}
					else
					{
						this._ID_PRICE_TAG = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBLPrice_tags");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLUsers_TBLReceipts", Storage="_TBLUsers", ThisKey="ID_USER", OtherKey="ID_USER", IsForeignKey=true)]
		public TBLUsers TBLUsers
		{
			get
			{
				return this._TBLUsers.Entity;
			}
			set
			{
				TBLUsers previousValue = this._TBLUsers.Entity;
				if (((previousValue != value) 
							|| (this._TBLUsers.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLUsers.Entity = null;
						previousValue.TBLReceipts.Remove(this);
					}
					this._TBLUsers.Entity = value;
					if ((value != null))
					{
						value.TBLReceipts.Add(this);
						this._ID_USER = value.ID_USER;
					}
					else
					{
						this._ID_USER = default(int);
					}
					this.SendPropertyChanged("TBLUsers");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USERS")]
	public partial class TBLUsers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_USER;
		
		private string _USER_NAME;
		
		private System.Nullable<int> _ID_AREA;
		
		private string _USER_STATE;
		
		private EntitySet<TBLReceipts> _TBLReceipts;
		
		private EntityRef<TBLAreas> _TBLAreas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_USERChanging(int value);
    partial void OnID_USERChanged();
    partial void OnUSER_NAMEChanging(string value);
    partial void OnUSER_NAMEChanged();
    partial void OnID_AREAChanging(System.Nullable<int> value);
    partial void OnID_AREAChanged();
    partial void OnUSER_STATEChanging(string value);
    partial void OnUSER_STATEChanged();
    #endregion
		
		public TBLUsers()
		{
			this._TBLReceipts = new EntitySet<TBLReceipts>(new Action<TBLReceipts>(this.attach_TBLReceipts), new Action<TBLReceipts>(this.detach_TBLReceipts));
			this._TBLAreas = default(EntityRef<TBLAreas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this.OnID_USERChanging(value);
					this.SendPropertyChanging();
					this._ID_USER = value;
					this.SendPropertyChanged("ID_USER");
					this.OnID_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NAME", DbType="VarChar(25)")]
		public string USER_NAME
		{
			get
			{
				return this._USER_NAME;
			}
			set
			{
				if ((this._USER_NAME != value))
				{
					this.OnUSER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._USER_NAME = value;
					this.SendPropertyChanged("USER_NAME");
					this.OnUSER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AREA", DbType="Int")]
		public System.Nullable<int> ID_AREA
		{
			get
			{
				return this._ID_AREA;
			}
			set
			{
				if ((this._ID_AREA != value))
				{
					if (this._TBLAreas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_AREAChanging(value);
					this.SendPropertyChanging();
					this._ID_AREA = value;
					this.SendPropertyChanged("ID_AREA");
					this.OnID_AREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_STATE", DbType="VarChar(10)")]
		public string USER_STATE
		{
			get
			{
				return this._USER_STATE;
			}
			set
			{
				if ((this._USER_STATE != value))
				{
					this.OnUSER_STATEChanging(value);
					this.SendPropertyChanging();
					this._USER_STATE = value;
					this.SendPropertyChanged("USER_STATE");
					this.OnUSER_STATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLUsers_TBLReceipts", Storage="_TBLReceipts", ThisKey="ID_USER", OtherKey="ID_USER")]
		public EntitySet<TBLReceipts> TBLReceipts
		{
			get
			{
				return this._TBLReceipts;
			}
			set
			{
				this._TBLReceipts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLAreas_TBLUsers", Storage="_TBLAreas", ThisKey="ID_AREA", OtherKey="ID_AREA", IsForeignKey=true)]
		public TBLAreas TBLAreas
		{
			get
			{
				return this._TBLAreas.Entity;
			}
			set
			{
				TBLAreas previousValue = this._TBLAreas.Entity;
				if (((previousValue != value) 
							|| (this._TBLAreas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLAreas.Entity = null;
						previousValue.TBLUsers.Remove(this);
					}
					this._TBLAreas.Entity = value;
					if ((value != null))
					{
						value.TBLUsers.Add(this);
						this._ID_AREA = value.ID_AREA;
					}
					else
					{
						this._ID_AREA = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBLAreas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBLReceipts(TBLReceipts entity)
		{
			this.SendPropertyChanging();
			entity.TBLUsers = this;
		}
		
		private void detach_TBLReceipts(TBLReceipts entity)
		{
			this.SendPropertyChanging();
			entity.TBLUsers = null;
		}
	}
	
	public partial class SP_pRETRIEVE_ALL_CUSTOMERResult
	{
		
		private int _ID_CUSTOMER;
		
		private string _CUSTOMER_NAME;
		
		private string _CUSTOMER_STATE;
		
		public SP_pRETRIEVE_ALL_CUSTOMERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CUSTOMER", DbType="Int NOT NULL")]
		public int ID_CUSTOMER
		{
			get
			{
				return this._ID_CUSTOMER;
			}
			set
			{
				if ((this._ID_CUSTOMER != value))
				{
					this._ID_CUSTOMER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(25)")]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this._CUSTOMER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_STATE", DbType="VarChar(10)")]
		public string CUSTOMER_STATE
		{
			get
			{
				return this._CUSTOMER_STATE;
			}
			set
			{
				if ((this._CUSTOMER_STATE != value))
				{
					this._CUSTOMER_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_pRETRIEVE_ALL_RECEIPTResult
	{
		
		private int _ID_RECEIPT;
		
		private string _CUSTOMER_NAME;
		
		private System.DateTime _DATE_RECEIPT;
		
		private int _QUANTITY;
		
		private System.Nullable<decimal> _TOTAL_RECEIPT;
		
		private System.Nullable<int> _ID_PRICE_TAG;
		
		private int _ID_USER;
		
		public SP_pRETRIEVE_ALL_RECEIPTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_RECEIPT", DbType="Int NOT NULL")]
		public int ID_RECEIPT
		{
			get
			{
				return this._ID_RECEIPT;
			}
			set
			{
				if ((this._ID_RECEIPT != value))
				{
					this._ID_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this._CUSTOMER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_RECEIPT", DbType="Date NOT NULL")]
		public System.DateTime DATE_RECEIPT
		{
			get
			{
				return this._DATE_RECEIPT;
			}
			set
			{
				if ((this._DATE_RECEIPT != value))
				{
					this._DATE_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Int NOT NULL")]
		public int QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this._QUANTITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_RECEIPT", DbType="Money")]
		public System.Nullable<decimal> TOTAL_RECEIPT
		{
			get
			{
				return this._TOTAL_RECEIPT;
			}
			set
			{
				if ((this._TOTAL_RECEIPT != value))
				{
					this._TOTAL_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRICE_TAG", DbType="Int")]
		public System.Nullable<int> ID_PRICE_TAG
		{
			get
			{
				return this._ID_PRICE_TAG;
			}
			set
			{
				if ((this._ID_PRICE_TAG != value))
				{
					this._ID_PRICE_TAG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
	}
	
	public partial class SP_pRETRIEVE_ALL_USERResult
	{
		
		private int _ID_USER;
		
		private string _USER_NAME;
		
		private System.Nullable<int> _ID_AREA;
		
		private string _USER_STATE;
		
		public SP_pRETRIEVE_ALL_USERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NAME", DbType="VarChar(25)")]
		public string USER_NAME
		{
			get
			{
				return this._USER_NAME;
			}
			set
			{
				if ((this._USER_NAME != value))
				{
					this._USER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AREA", DbType="Int")]
		public System.Nullable<int> ID_AREA
		{
			get
			{
				return this._ID_AREA;
			}
			set
			{
				if ((this._ID_AREA != value))
				{
					this._ID_AREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_STATE", DbType="VarChar(10)")]
		public string USER_STATE
		{
			get
			{
				return this._USER_STATE;
			}
			set
			{
				if ((this._USER_STATE != value))
				{
					this._USER_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_pRETRIEVE_CUSTOMERResult
	{
		
		private int _ID_CUSTOMER;
		
		private string _CUSTOMER_NAME;
		
		private string _CUSTOMER_STATE;
		
		public SP_pRETRIEVE_CUSTOMERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CUSTOMER", DbType="Int NOT NULL")]
		public int ID_CUSTOMER
		{
			get
			{
				return this._ID_CUSTOMER;
			}
			set
			{
				if ((this._ID_CUSTOMER != value))
				{
					this._ID_CUSTOMER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(25)")]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this._CUSTOMER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_STATE", DbType="VarChar(10)")]
		public string CUSTOMER_STATE
		{
			get
			{
				return this._CUSTOMER_STATE;
			}
			set
			{
				if ((this._CUSTOMER_STATE != value))
				{
					this._CUSTOMER_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_pRETRIEVE_RECEIPTResult
	{
		
		private int _ID_RECEIPT;
		
		private string _CUSTOMER_NAME;
		
		private System.DateTime _DATE_RECEIPT;
		
		private int _QUANTITY;
		
		private System.Nullable<decimal> _TOTAL_RECEIPT;
		
		private System.Nullable<int> _ID_PRICE_TAG;
		
		private int _ID_USER;
		
		public SP_pRETRIEVE_RECEIPTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_RECEIPT", DbType="Int NOT NULL")]
		public int ID_RECEIPT
		{
			get
			{
				return this._ID_RECEIPT;
			}
			set
			{
				if ((this._ID_RECEIPT != value))
				{
					this._ID_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this._CUSTOMER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_RECEIPT", DbType="Date NOT NULL")]
		public System.DateTime DATE_RECEIPT
		{
			get
			{
				return this._DATE_RECEIPT;
			}
			set
			{
				if ((this._DATE_RECEIPT != value))
				{
					this._DATE_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Int NOT NULL")]
		public int QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this._QUANTITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_RECEIPT", DbType="Money")]
		public System.Nullable<decimal> TOTAL_RECEIPT
		{
			get
			{
				return this._TOTAL_RECEIPT;
			}
			set
			{
				if ((this._TOTAL_RECEIPT != value))
				{
					this._TOTAL_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRICE_TAG", DbType="Int")]
		public System.Nullable<int> ID_PRICE_TAG
		{
			get
			{
				return this._ID_PRICE_TAG;
			}
			set
			{
				if ((this._ID_PRICE_TAG != value))
				{
					this._ID_PRICE_TAG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
	}
	
	public partial class SP_pRETRIEVE_USERResult
	{
		
		private int _ID_USER;
		
		private string _USER_NAME;
		
		private System.Nullable<int> _ID_AREA;
		
		private string _USER_STATE;
		
		public SP_pRETRIEVE_USERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NAME", DbType="VarChar(25)")]
		public string USER_NAME
		{
			get
			{
				return this._USER_NAME;
			}
			set
			{
				if ((this._USER_NAME != value))
				{
					this._USER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AREA", DbType="Int")]
		public System.Nullable<int> ID_AREA
		{
			get
			{
				return this._ID_AREA;
			}
			set
			{
				if ((this._ID_AREA != value))
				{
					this._ID_AREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_STATE", DbType="VarChar(10)")]
		public string USER_STATE
		{
			get
			{
				return this._USER_STATE;
			}
			set
			{
				if ((this._USER_STATE != value))
				{
					this._USER_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_ALL_AREAResult
	{
		
		private int _ID_AREA;
		
		private string _AREA_NAME;
		
		private string _AREA_STATE;
		
		public SP_RETRIEVE_ALL_AREAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AREA", DbType="Int NOT NULL")]
		public int ID_AREA
		{
			get
			{
				return this._ID_AREA;
			}
			set
			{
				if ((this._ID_AREA != value))
				{
					this._ID_AREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA_NAME", DbType="VarChar(25)")]
		public string AREA_NAME
		{
			get
			{
				return this._AREA_NAME;
			}
			set
			{
				if ((this._AREA_NAME != value))
				{
					this._AREA_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA_STATE", DbType="VarChar(10)")]
		public string AREA_STATE
		{
			get
			{
				return this._AREA_STATE;
			}
			set
			{
				if ((this._AREA_STATE != value))
				{
					this._AREA_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_ALL_CUSTOMERResult
	{
		
		private int _ID_CUSTOMER;
		
		private string _CUSTOMER_NAME;
		
		private string _CUSTOMER_STATE;
		
		public SP_RETRIEVE_ALL_CUSTOMERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CUSTOMER", DbType="Int NOT NULL")]
		public int ID_CUSTOMER
		{
			get
			{
				return this._ID_CUSTOMER;
			}
			set
			{
				if ((this._ID_CUSTOMER != value))
				{
					this._ID_CUSTOMER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(25)")]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this._CUSTOMER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_STATE", DbType="VarChar(10)")]
		public string CUSTOMER_STATE
		{
			get
			{
				return this._CUSTOMER_STATE;
			}
			set
			{
				if ((this._CUSTOMER_STATE != value))
				{
					this._CUSTOMER_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_ALL_PRICE_TAGResult
	{
		
		private int _ID_PRICE_TAG;
		
		private System.Nullable<decimal> _TOTAL_PRICE;
		
		private string _DESCRIP_PRICE;
		
		private string _PRICE_TAG_STATE;
		
		public SP_RETRIEVE_ALL_PRICE_TAGResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRICE_TAG", DbType="Int NOT NULL")]
		public int ID_PRICE_TAG
		{
			get
			{
				return this._ID_PRICE_TAG;
			}
			set
			{
				if ((this._ID_PRICE_TAG != value))
				{
					this._ID_PRICE_TAG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_PRICE", DbType="Money")]
		public System.Nullable<decimal> TOTAL_PRICE
		{
			get
			{
				return this._TOTAL_PRICE;
			}
			set
			{
				if ((this._TOTAL_PRICE != value))
				{
					this._TOTAL_PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIP_PRICE", DbType="VarChar(10)")]
		public string DESCRIP_PRICE
		{
			get
			{
				return this._DESCRIP_PRICE;
			}
			set
			{
				if ((this._DESCRIP_PRICE != value))
				{
					this._DESCRIP_PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE_TAG_STATE", DbType="VarChar(10)")]
		public string PRICE_TAG_STATE
		{
			get
			{
				return this._PRICE_TAG_STATE;
			}
			set
			{
				if ((this._PRICE_TAG_STATE != value))
				{
					this._PRICE_TAG_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_ALL_RECEIPTResult
	{
		
		private int _ID_RECEIPT;
		
		private string _CUSTOMER_NAME;
		
		private System.DateTime _DATE_RECEIPT;
		
		private int _QUANTITY;
		
		private System.Nullable<decimal> _TOTAL_RECEIPT;
		
		private System.Nullable<int> _ID_PRICE_TAG;
		
		private int _ID_USER;
		
		public SP_RETRIEVE_ALL_RECEIPTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_RECEIPT", DbType="Int NOT NULL")]
		public int ID_RECEIPT
		{
			get
			{
				return this._ID_RECEIPT;
			}
			set
			{
				if ((this._ID_RECEIPT != value))
				{
					this._ID_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this._CUSTOMER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_RECEIPT", DbType="Date NOT NULL")]
		public System.DateTime DATE_RECEIPT
		{
			get
			{
				return this._DATE_RECEIPT;
			}
			set
			{
				if ((this._DATE_RECEIPT != value))
				{
					this._DATE_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Int NOT NULL")]
		public int QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this._QUANTITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_RECEIPT", DbType="Money")]
		public System.Nullable<decimal> TOTAL_RECEIPT
		{
			get
			{
				return this._TOTAL_RECEIPT;
			}
			set
			{
				if ((this._TOTAL_RECEIPT != value))
				{
					this._TOTAL_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRICE_TAG", DbType="Int")]
		public System.Nullable<int> ID_PRICE_TAG
		{
			get
			{
				return this._ID_PRICE_TAG;
			}
			set
			{
				if ((this._ID_PRICE_TAG != value))
				{
					this._ID_PRICE_TAG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_ALL_USERResult
	{
		
		private int _ID_USER;
		
		private string _USER_NAME;
		
		private System.Nullable<int> _ID_AREA;
		
		private string _USER_STATE;
		
		public SP_RETRIEVE_ALL_USERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NAME", DbType="VarChar(25)")]
		public string USER_NAME
		{
			get
			{
				return this._USER_NAME;
			}
			set
			{
				if ((this._USER_NAME != value))
				{
					this._USER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AREA", DbType="Int")]
		public System.Nullable<int> ID_AREA
		{
			get
			{
				return this._ID_AREA;
			}
			set
			{
				if ((this._ID_AREA != value))
				{
					this._ID_AREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_STATE", DbType="VarChar(10)")]
		public string USER_STATE
		{
			get
			{
				return this._USER_STATE;
			}
			set
			{
				if ((this._USER_STATE != value))
				{
					this._USER_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_AREAResult
	{
		
		private int _ID_AREA;
		
		private string _AREA_NAME;
		
		private string _AREA_STATE;
		
		public SP_RETRIEVE_AREAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AREA", DbType="Int NOT NULL")]
		public int ID_AREA
		{
			get
			{
				return this._ID_AREA;
			}
			set
			{
				if ((this._ID_AREA != value))
				{
					this._ID_AREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA_NAME", DbType="VarChar(25)")]
		public string AREA_NAME
		{
			get
			{
				return this._AREA_NAME;
			}
			set
			{
				if ((this._AREA_NAME != value))
				{
					this._AREA_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA_STATE", DbType="VarChar(10)")]
		public string AREA_STATE
		{
			get
			{
				return this._AREA_STATE;
			}
			set
			{
				if ((this._AREA_STATE != value))
				{
					this._AREA_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_AUTHENTICATIONResult
	{
		
		private int _ID_USER;
		
		private string _USER_NICKNAME;
		
		private string _PASSWORD;
		
		private int _ID_AREA;
		
		private string _AUTHENTIC_STATE;
		
		public SP_RETRIEVE_AUTHENTICATIONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NICKNAME", DbType="VarChar(40)")]
		public string USER_NICKNAME
		{
			get
			{
				return this._USER_NICKNAME;
			}
			set
			{
				if ((this._USER_NICKNAME != value))
				{
					this._USER_NICKNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(20)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this._PASSWORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AREA", DbType="Int NOT NULL")]
		public int ID_AREA
		{
			get
			{
				return this._ID_AREA;
			}
			set
			{
				if ((this._ID_AREA != value))
				{
					this._ID_AREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTHENTIC_STATE", DbType="VarChar(10)")]
		public string AUTHENTIC_STATE
		{
			get
			{
				return this._AUTHENTIC_STATE;
			}
			set
			{
				if ((this._AUTHENTIC_STATE != value))
				{
					this._AUTHENTIC_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_CUSTOMERResult
	{
		
		private int _ID_CUSTOMER;
		
		private string _CUSTOMER_NAME;
		
		private string _CUSTOMER_STATE;
		
		public SP_RETRIEVE_CUSTOMERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CUSTOMER", DbType="Int NOT NULL")]
		public int ID_CUSTOMER
		{
			get
			{
				return this._ID_CUSTOMER;
			}
			set
			{
				if ((this._ID_CUSTOMER != value))
				{
					this._ID_CUSTOMER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(25)")]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this._CUSTOMER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_STATE", DbType="VarChar(10)")]
		public string CUSTOMER_STATE
		{
			get
			{
				return this._CUSTOMER_STATE;
			}
			set
			{
				if ((this._CUSTOMER_STATE != value))
				{
					this._CUSTOMER_STATE = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_PRICE_TAGResult
	{
		
		private int _ID_PRICE_TAG;
		
		private System.Nullable<decimal> _TOTAL_PRICE;
		
		private string _DESCRIP_PRICE;
		
		public SP_RETRIEVE_PRICE_TAGResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRICE_TAG", DbType="Int NOT NULL")]
		public int ID_PRICE_TAG
		{
			get
			{
				return this._ID_PRICE_TAG;
			}
			set
			{
				if ((this._ID_PRICE_TAG != value))
				{
					this._ID_PRICE_TAG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_PRICE", DbType="Money")]
		public System.Nullable<decimal> TOTAL_PRICE
		{
			get
			{
				return this._TOTAL_PRICE;
			}
			set
			{
				if ((this._TOTAL_PRICE != value))
				{
					this._TOTAL_PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIP_PRICE", DbType="VarChar(10)")]
		public string DESCRIP_PRICE
		{
			get
			{
				return this._DESCRIP_PRICE;
			}
			set
			{
				if ((this._DESCRIP_PRICE != value))
				{
					this._DESCRIP_PRICE = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_RECEIPTResult
	{
		
		private int _ID_RECEIPT;
		
		private string _CUSTOMER_NAME;
		
		private System.DateTime _DATE_RECEIPT;
		
		private int _QUANTITY;
		
		private System.Nullable<decimal> _TOTAL_RECEIPT;
		
		private System.Nullable<int> _ID_PRICE_TAG;
		
		private int _ID_USER;
		
		public SP_RETRIEVE_RECEIPTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_RECEIPT", DbType="Int NOT NULL")]
		public int ID_RECEIPT
		{
			get
			{
				return this._ID_RECEIPT;
			}
			set
			{
				if ((this._ID_RECEIPT != value))
				{
					this._ID_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this._CUSTOMER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_RECEIPT", DbType="Date NOT NULL")]
		public System.DateTime DATE_RECEIPT
		{
			get
			{
				return this._DATE_RECEIPT;
			}
			set
			{
				if ((this._DATE_RECEIPT != value))
				{
					this._DATE_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Int NOT NULL")]
		public int QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this._QUANTITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_RECEIPT", DbType="Money")]
		public System.Nullable<decimal> TOTAL_RECEIPT
		{
			get
			{
				return this._TOTAL_RECEIPT;
			}
			set
			{
				if ((this._TOTAL_RECEIPT != value))
				{
					this._TOTAL_RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRICE_TAG", DbType="Int")]
		public System.Nullable<int> ID_PRICE_TAG
		{
			get
			{
				return this._ID_PRICE_TAG;
			}
			set
			{
				if ((this._ID_PRICE_TAG != value))
				{
					this._ID_PRICE_TAG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
	}
	
	public partial class SP_RETRIEVE_USERResult
	{
		
		private int _ID_USER;
		
		private string _USER_NAME;
		
		private System.Nullable<int> _ID_AREA;
		
		private string _USER_STATE;
		
		public SP_RETRIEVE_USERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="Int NOT NULL")]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this._ID_USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NAME", DbType="VarChar(25)")]
		public string USER_NAME
		{
			get
			{
				return this._USER_NAME;
			}
			set
			{
				if ((this._USER_NAME != value))
				{
					this._USER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AREA", DbType="Int")]
		public System.Nullable<int> ID_AREA
		{
			get
			{
				return this._ID_AREA;
			}
			set
			{
				if ((this._ID_AREA != value))
				{
					this._ID_AREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_STATE", DbType="VarChar(10)")]
		public string USER_STATE
		{
			get
			{
				return this._USER_STATE;
			}
			set
			{
				if ((this._USER_STATE != value))
				{
					this._USER_STATE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
